site:
  title: "Lyean's Portfolio"
  description: "Lyean's Web Developer Portfolio"
personal:
  welcome: 'Hey There, Welcome To My Portfolio'
  brief: 'My name is Lyean and here you will find my most relevant software projects and a little about my history!'
  phone: '09677633375'
  email: 'lyean1500@gmail.com'
  socialNetworks:
    github: 'https://github.com/Lyean1'
    linkedin: 'https://www.linkedin.com/in/say-lyean-10381827a/'
